import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebar: SidebarsConfig = {
  sampleSidebar: [
    {
      type: "doc",
      id: "Sample/index",
      label: "はじめに",
    },
    {
      type: "category",
      label: "Mermaid例",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "Sample/Mermaid/flowChart",
          label: "フローチャート図",
        },
        {
          type: "doc",
          id: "Sample/Mermaid/erDiagram",
          label: "ER図",
        },
        {
          type: "doc",
          id: "Sample/Mermaid/gannt",
          label: "ガントチャート図",
        },
        {
          type: "doc",
          id: "Sample/Mermaid/sequenceDiagram",
          label: "シーケンス図",
        },
      ],
    },
    {
      type: "category",
      label: "GoogleDrive",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "Sample/GoogleDrive/excel",
          label: "Excel",
        },
        {
          type: "doc",
          id: "Sample/GoogleDrive/powerpoint",
          label: "PowerPoint",
        },
        {
          type: "doc",
          id: "Sample/GoogleDrive/pdf",
          label: "PDF",
        },
      ],
    },
    {
      type: "category",
      label: "OpenAPI",
      collapsed: false,
      items: [
        {
          type: "category",
          label: "Pet",
          collapsed: true,
          items: [
            {
              type: "doc",
              id: "Sample/OpenAPI/autoGeneratedFile/add-pet",
              label: "Add a new pet",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "Sample/OpenAPI/autoGeneratedFile/find-pets-by-status",
              label: "Find pets by status",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "Sample/OpenAPI/autoGeneratedFile/find-pets-by-tags",
              label: "Find pets by tags",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "Sample/OpenAPI/autoGeneratedFile/update-pet",
              label: "Update a pet",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "Sample/OpenAPI/autoGeneratedFile/upload-file",
              label: "Upload an image",
              className: "api-method post",
            },
          ],
        },
        {
          type: "category",
          label: "Store",
          collapsed: true,
          items: [
            {
              type: "doc",
              id: "Sample/OpenAPI/autoGeneratedFile/get-inventory",
              label: "Returns pet inventories",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "Sample/OpenAPI/autoGeneratedFile/place-order",
              label: "Place an order",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "Sample/OpenAPI/autoGeneratedFile/delete-order",
              label: "Delete purchase order",
              className: "api-method delete",
            },
          ],
        },
        {
          type: "category",
          label: "User",
          collapsed: true,
          items: [
            {
              type: "doc",
              id: "Sample/OpenAPI/autoGeneratedFile/create-user",
              label: "Create User",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "Sample/OpenAPI/autoGeneratedFile/create-users-with-list-input",
              label: "Creates list of users",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "Sample/OpenAPI/autoGeneratedFile/login-user",
              label: "Login user",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "Sample/OpenAPI/autoGeneratedFile/logout-user",
              label: "Logout user",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "Sample/OpenAPI/autoGeneratedFile/get-user-by-name",
              label: "Get User by user name",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "Sample/OpenAPI/autoGeneratedFile/update-user",
              label: "Update user",
              className: "api-method put",
            },
          ],
        },
      ],
    },
  ],
};

export default sidebar.sampleSidebar;
